version: 0.{build}
branches:
  only:
  - master
nuget:
  project_feed: true
configuration: Debug

environment:
  encFileKey:
    secure: IS92sMB8DjOsUUuLZRWCEHtM3s4a0TWtWojhyOXsxqk=

build:
  project: appveyor-test2.sln
  verbosity: minimal

artifacts:
- path: appveyor-test2\bin
  name: output
deploy:
- provider: FTP
  on:
    APPVEYOR_REPO_TAG: true
  host: voyager.fayretech.com
  protocol: sftp
  username: talkingflightmonitor
  password:
    secure: gsDOGtodux/gAPPDTybI5w==
  folder: /tfm-snapshots
notifications:
- provider: Email
  to:
  - jfayre@gmail.com
  subject: TFM build
  on_build_success: true
  on_build_failure: true
